coffee/urls.py
from django.urls import path

from coffee.views.brand import BrandDetailView
from coffee.views.brand import BrandListView
from coffee.views.coffee import CoffeeDetailView
from coffee.views.coffee import CoffeeListView
from coffee.views.legal_entity import EntityDetailView
from coffee.views.legal_entity import EntityListView

app_name = 'coffee'

urlpatterns = [
    path('entity/', EntityListView.as_view(), name='entity-list'),
    path('entity/<int:pk>/', EntityDetailView.as_view(), name='entity-detail'),

    path('brand/', BrandListView.as_view(), name='brand-list'),
    path('brand/<int:pk>/', BrandDetailView.as_view(), name='brand-detail'),

    path('coffee/', CoffeeListView.as_view(), name='coffee-list'),
    path('coffee/<int:pk>/', CoffeeDetailView.as_view(), name='coffee-detail')
]

judge/urls.py
"""
"""
from django.urls import path

from judge.views.auth import LoginFormView, LogoutRedirectView
from judge.views.profile import UpdateProfileView, ProfileDetailView

app_name = 'judge'

urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutRedirectView.as_view(), name='logout'),

    path('profile/', ProfileDetailView.as_view(), name='profile-show'),
    path('profile/edit/', UpdateProfileView.as_view(), name='profile-edit')
]

lovecoffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from lovecoffee.views.basic import ContactFormView

urlpatterns = [
    path('', TemplateView.as_view(template_name='basic/index.html'), name='lovecoffee-home'),
    path('about/', TemplateView.as_view(template_name='basic/about.html'), name='lovecoffee-about'),
    path('services/', TemplateView.as_view(template_name='basic/services.html'), name='lovecoffee-services'),
    path('contact/', ContactFormView.as_view(), name='lovecoffee-contact'),

    path('admin/', admin.site.urls),

    path('coffee/', include('coffee.urls', namespace='coffee')),

    path('judge/', include('judge.urls', namespace='judge')),

    path('rating/', include('rating.urls', namespace='rating'))
]

lovecoffee/forms/contact.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True, max_length=150)
    email_address = forms.EmailField(required=True, max_length=150)
    message = forms.CharField(required=True, widget=forms.Textarea, max_length=2000)

lovecoffee/views/basic.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import FormView

from lovecoffee.forms.contact import ContactForm


class ContactFormView(FormView):
    template_name = 'basic/contact.html'
    form_class = ContactForm

    # TODO suares надо понять как использовать это
    # success_url = reverse('lovecoffee-home')

    def form_valid(self, form):
        form = ContactForm(self.request.POST)
        # TODO suares looks like this validation is not necessary. We access to form_valid only if form is valid
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'name': form.cleaned_data['name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message']
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'admin_from@example.com', ['admin_to@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            return HttpResponseRedirect(reverse('lovecoffee-home'))

        # TODO suares походу сделано не очень, то есть если все ок то делаем редирект, зачем тогда этот return
        return super().form_valid(form)

lovecoffee/templates/generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    {% block title %}<title>Love Coffee</title>{% endblock %}

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'basic/assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'basic/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'basic/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'basic/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'basic/assets/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Moderna - v4.10.1
    * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container d-flex justify-content-between align-items-center">

        <div class="logo">
            <h1 class="text-light"><a href="{% url 'lovecoffee-home' %}"><span>Moderna</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="active " href="{% url 'lovecoffee-home' %}">Home</a></li>
                <li><a href="{% url 'coffee:entity-list' %}">Entity</a></li>
                <li><a href="{% url 'coffee:brand-list' %}">Brands</a></li>
                <li><a href="{% url 'coffee:coffee-list' %}">Coffee</a></li>
                <li><a href="{% url 'lovecoffee-services' %}">Services</a></li>
                <li><a href="{% url 'lovecoffee-about' %}">About</a></li>
                {#                <li><a href="portfolio.html">Portfolio</a></li>#}
                {#                <li><a href="team.html">Team</a></li>#}
                {#                <li><a href="blog.html">Blog</a></li>#}
                <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                            <ul>
                                <li><a href="#">Deep Drop Down 1</a></li>
                                <li><a href="#">Deep Drop Down 2</a></li>
                                <li><a href="#">Deep Drop Down 3</a></li>
                                <li><a href="#">Deep Drop Down 4</a></li>
                                <li><a href="#">Deep Drop Down 5</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'lovecoffee-contact' %}">Contact Us</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        <!-- TODO suares use logo -->
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'judge:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'judge:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</header><!-- End Header -->

{% block content %}{% endblock %}

<!-- ======= Footer ======= -->
<footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-newsletter">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h4>Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                </div>
                <div class="col-lg-6">
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'lovecoffee-home' %}">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'lovecoffee-about' %}">About us</a></li>
                        <li>
                            <i class="bx bx-chevron-right"></i> <a href="{% url 'lovecoffee-services' %}">Services</a>
                        </li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Contact Us</h4>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022<br>
                        United States <br><br>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>

                </div>

                <div class="col-lg-3 col-md-6 footer-info">
                    <h3>About Moderna</h3>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita
                        valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<link href="{% static 'basic/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">

<!-- Vendor JS Files -->
<script src="{% static 'basic/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'basic/assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'basic/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'basic/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'basic/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'basic/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'basic/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'basic/assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'basic/assets/js/main.js' %}"></script>

</body>

</html>

lovecoffee/templates/pagination.html
<div class="row">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>