coffee/urls.py
from django.urls import path

from coffee.views.brand import BrandDetailView
from coffee.views.brand import BrandListView
from coffee.views.coffee import CoffeeDetailView
from coffee.views.coffee import CoffeeListView
from coffee.views.legal_entity import EntityDetailView
from coffee.views.legal_entity import EntityListView

app_name = 'coffee'

urlpatterns = [
    path('entity/', EntityListView.as_view(), name='entity-list'),
    path('entity/<int:pk>/', EntityDetailView.as_view(), name='entity-detail'),

    path('brand/', BrandListView.as_view(), name='brand-list'),
    path('brand/<int:pk>/', BrandDetailView.as_view(), name='brand-detail'),

    path('coffee/', CoffeeListView.as_view(), name='coffee-list'),
    path('coffee/<int:pk>/', CoffeeDetailView.as_view(), name='coffee-detail')
]

judge/urls.py
"""
"""
from django.urls import path

from judge.views.auth import LoginFormView, LogoutRedirectView
from judge.views.profile import UpdateProfileView, ProfileDetailView

app_name = 'judge'

urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutRedirectView.as_view(), name='logout'),

    path('profile/', ProfileDetailView.as_view(), name='profile-show'),
    path('profile/edit/', UpdateProfileView.as_view(), name='profile-edit')
]

lovecoffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from lovecoffee.views.basic import ContactFormView

urlpatterns = [
    path('', TemplateView.as_view(template_name='basic/index.html'), name='lovecoffee-home'),
    path('about/', TemplateView.as_view(template_name='basic/about.html'), name='lovecoffee-about'),
    path('services/', TemplateView.as_view(template_name='basic/services.html'), name='lovecoffee-services'),
    path('contact/', ContactFormView.as_view(), name='lovecoffee-contact'),

    path('admin/', admin.site.urls),

    path('coffee/', include('coffee.urls', namespace='coffee')),

    path('judge/', include('judge.urls', namespace='judge')),

    path('rating/', include('rating.urls', namespace='rating'))
]

coffee/models/brand.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from coffee.models.legal_entity import LegalEntity


class Brand(TimeStampedModel):
    name = models.CharField(verbose_name=_('Nombre'), max_length=255)

    legal_entity = models.ForeignKey(
        LegalEntity,
        verbose_name=_('Entidad'),
        on_delete=models.RESTRICT,
        related_name='entity'
    )

    is_active = models.BooleanField(verbose_name=_('Activo'), default=True)

    class Meta:
        verbose_name = _('Marca')
        verbose_name_plural = _('Marcas')
        constraints = [
            models.UniqueConstraint(
                name='unique_coffee_brand_name_legal_entity',
                fields=['name', 'legal_entity']
            )
        ]

    def __str__(self):
        return f'{self.name}(pk: {self.pk})'

coffee/models/coffee_address.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from coffee.models.brand import Brand
from common.models.city import City


class CoffeeAddress(TimeStampedModel):
    city = models.ForeignKey(City, verbose_name=_('Localidad'), related_name='city', on_delete=models.RESTRICT)

    # TODO should I divide address in to fields
    address = models.TextField(verbose_name=_('Dirección'))

    brand = models.ForeignKey(Brand, verbose_name=_('Marca'), on_delete=models.RESTRICT, related_name='brand')

    is_active = models.BooleanField(verbose_name=_('Activo'), default=True)

    class Meta:
        verbose_name = _('Dirección')
        verbose_name_plural = _('Direcciones')
        constraints = [
            models.UniqueConstraint(
                name='unique_coffee_coffee_address_city_address_brand',
                fields=['city', 'address', 'brand']
            )
        ]

    def __str__(self):
        return f'{self.address}(pk: {self.pk} brand_id: {self.brand_id})'

coffee/models/legal_entity.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class LegalEntity(TimeStampedModel):
    name = models.CharField(verbose_name=_('Nombre'), unique=True, max_length=255)

    # TODO do I need to add related_name
    parent = models.ForeignKey('self', verbose_name=_('Padre'), blank=True, null=True, on_delete=models.RESTRICT)

    is_active = models.BooleanField(verbose_name=_('Activo'), default=True)

    class Meta:
        verbose_name = _('Entidad')
        verbose_name_plural = _('Entidades')

    def __str__(self):
        return f'{self.name}(pk: {self.pk})'

coffee/views.py
# Create your views here.
from datetime import datetime

from django.http import HttpResponse


def index(request):
    now = datetime.now()
    html = f'''
    <html>
        <body>
            <h1>Hello!</h1>
            <p>The current time is {now}.</p>
        </body>
    </html>
    '''
    return HttpResponse(html)

coffee/views/brand.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from coffee.models.brand import Brand as BrandModel
from coffee.persistence.brand.brand import Brand
from coffee.views.filters.brand import BrandFilter


class BrandListView(ListView):
    model = BrandModel
    template_name = 'brand/list.html'
    context_object_name = 'brands'
    paginate_by = 8

    def get_queryset(self, *args, **kwargs):
        return BrandFilter(self.request.GET, queryset=Brand.get_brands()).qs


class BrandDetailView(DetailView):
    model = BrandModel
    context_object_name = 'brand'
    template_name = 'brand/detail.html'

coffee/views/coffee.py
from django.views.generic import DetailView, ListView

from coffee.models.coffee_address import CoffeeAddress as CoffeeAddressModel
from coffee.persistence.coffee_address.coffee_address import CoffeeAddress
from coffee.views.filters.coffee_address import CoffeeAddressFilter


class CoffeeListView(ListView):
    model = CoffeeAddressModel
    template_name = 'coffee/list.html'
    context_object_name = 'coffees'
    paginate_by = 8

    def get_queryset(self, *args, **kwargs):
        return CoffeeAddressFilter(self.request.GET, queryset=CoffeeAddress.get_coffees()).qs


class CoffeeDetailView(DetailView):
    model = CoffeeAddressModel
    context_object_name = 'coffee'
    template_name = 'coffee/detail.html'

coffee/views/legal_entity.py
from django.views.generic import DetailView
from django.views.generic import ListView

from coffee.models.legal_entity import LegalEntity as LegalEntityModel
from coffee.persistence.legal_entity.legal_entity import LegalEntity
from coffee.views.filters.legal_entity import LegalEntityFilter


class EntityListView(ListView):
    model = LegalEntityModel
    template_name = 'entity/list.html'
    context_object_name = 'entities'
    paginate_by = 8

    def get_queryset(self, *args, **kwargs):
        return LegalEntityFilter(self.request.GET, queryset=LegalEntity.get_entities()).qs


class EntityDetailView(DetailView):
    model = LegalEntityModel
    context_object_name = 'entity'
    template_name = 'entity/detail.html'

coffee/templates/coffee/detail.html
{% extends 'generic.html' %}
{% load static %}

{% block content %}
    <section id="hero" class="d-flex justify-cntent-center align-items-center">
        <div id="heroCarousel" class="container carousel carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

            <!-- Slide 1 -->
            <div class="carousel-item active">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Moderna</span></h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 2 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 3 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
            </a>

        </div>
    </section>

    <main id="main">

        <section class="services">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
                        <div class="icon-box icon-box-pink">
                            <h4 class="title">{{ coffee.address }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}

coffee/templates/coffee/index.html
{% extends 'generic.html' %}
{% load static %}

{% block content %}
    <section id="hero" class="d-flex justify-cntent-center align-items-center">
        <div id="heroCarousel" class="container carousel carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

            <!-- Slide 1 -->
            <div class="carousel-item active">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Moderna</span></h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 2 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 3 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
            </a>

        </div>
    </section>

    <main id="main">

        <section class="services">
            <div class="container">
                <div class="row">
                    {% for coffee in coffees %}
                        <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
                            <div class="icon-box icon-box-pink">
                                <div class="icon"><i class="bx bxl-dribbble"></i></div>
                                <h4 class="title">
                                    <a href="{% url 'coffee:coffee-detail' pk=coffee.pk %}">Go to coffee</a>
                                </h4>
                                <h4 class="title">
                                    <a href="{% url 'coffee:brand-detail' pk=coffee.brand_id %}">
                                        {{ coffee.brand.name }}
                                    </a>
                                </h4>
                                <p class="description">{{ coffee.city.name }}, {{ coffee.address }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>

{% endblock %}

coffee/templates/coffee/list.html
{% extends 'generic.html' %}
{% load static %}

{% block content %}
    <section id="hero" class="d-flex justify-cntent-center align-items-center">
        <div id="heroCarousel" class="container carousel carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

            <!-- Slide 1 -->
            <div class="carousel-item active">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Moderna</span></h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 2 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <!-- Slide 3 -->
            <div class="carousel-item">
                <div class="carousel-container">
                    <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                    <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid.
                        Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut.
                        Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore
                        modi architecto.</p>
                    <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
                </div>
            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
            </a>

        </div>
    </section>

    <main id="main">

        <section class="services">
            <div class="container">
                <div class="row">
                    {% for coffee in coffees %}
                        <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
                            <div class="icon-box icon-box-pink">
                                <div class="icon"><i class="bx bxl-dribbble"></i></div>
                                <h4 class="title">
                                    <a href="{% url 'coffee:coffee-detail' pk=coffee.pk %}">Go to coffee</a>
                                </h4>
                                <h4 class="title">
                                    <a href="{% url 'coffee:brand-detail' pk=coffee.brand_id %}">
                                        {{ coffee.brand.name }}
                                    </a>
                                </h4>
                                <p class="description">{{ coffee.city.name }}, {{ coffee.address }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% include "pagination.html" %}
            </div>
        </section>

    </main>

{% endblock %}